export const AUTH_REQUEST="AUTH_REQUEST";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAILURE="AUTH_FAILURE";
export const AUTH_LOGOUT="AUTH_LOGOUT";

export const GOODS_REQUEST="GOODS_REQUEST";
export const GOODS_SUCCESS="GOODS_SUCCESS";
export const GOODS_FAILURE="GOODS_FAILURE";
export const GOOD_INFO_SUCCESS="GOOD_INFO_SUCCESS";

export const CATEGORY_REQUEST="CATEGORY_REQUEST";
export const CATEGORY_SUCCESS="CATEGORY_SUCCESS";
export const CATEGORY_FAILURE="CATEGORY_FAILURE";